### PR TITLE
Chore/143 update dependencies

### PR DESCRIPTION
**Pull request by caraya**
OK, I think this is it. Sorry for the spam in the PRs, I'm learning how to do it

### CODE REVIEW

**Comment by DanielRuf** [comment]
You can close the other PR if this PR here is the right one.

**Comment by DanielRuf** [comment]
It lookd like this was released as minor / patch release but should have been some major release as these were upgrades and it was not tested with Node 12 and older. terminal-kit requires Node 14 since 2.0.0.

**Comment by DanielRuf** [comment]
It looks like this was released as minor / patch release but should have been some major release as these were upgrades and it was not tested with Node 12 and older. terminal-kit requires Node 14 since 2.0.0.

**Comment by joeworkman** [comment]
I am running everything via node 14. What issues are you having? I will read up on this to get node 12 back. Although at this point does it even matter since Node 14 is the LTS version?

The CLI has been broken for a very long time. I tried to get it at least somewhat functional again. However, it's a lot to maintain for something that could just be a 5 line shell script.

**Comment by caraya** [comment]
@joeworkman  Terminal-kit after 2.0.0 will not work with Node 12.

**Comment by caraya** [comment]
Both Node 12 and 14 are LTS releases

**Comment by joeworkman** [comment]
Yes. That was a boneheaded comment by me. I had not intended to break node 12. However, now that it's done,

**Comment by caraya** [comment]
It is not really usable, you're right...  but what's the alternative other than fixing it? Is it really to create a new one?

**Comment by joeworkman** [comment]
The alternative is to simply run a few common commands via terminal or put them into your own shell script. 

```sh
git clone https://github.com/foundation/foundation-sites-template.git 
cd foundation-sites-template
rm -rf .git
yarn install
```

```sh
git clone https://github.com/foundation/foundation-zurb-template.git 
cd foundation-zurb-template
rm -rf .git
yarn install
```

**Comment by caraya** [comment]
Again, that is true. However most of the time people have been directed to use the CLI and it also provides commands that you can't do with just a shell script or at least not easily.

People are still expecting the CLI to work and to do otherwise without taking it off circulation is irresponsible, if the project will not be maintained it should be archived and expectations adjusted accordingly

**Comment by joeworkman** [comment]
I agree.

**Pull request merged**
